version: '3.9'
services:
  mathocr-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mathocr-api
    env_file:
      - ./02_main/.env
    ports:
      - "8000:8000"
    volumes:
      - ./02_main/runtime:/app/runtime
    restart: unless-stopped
